version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build -p handlers/$MODULE_NAME --scan

  post_build:
    commands:
      - echo Build completed on `date`
      - JAR_FILE=$(find handlers/$MODULE_NAME/build/libs -name "*-all.jar" -type f)
      - AWS_S3_KEY=$(basename "$JAR_FILE")
      - aws s3 cp "$JAR_FILE" "s3://$BUCKET_NAME/$MODULE_NAME/$AWS_S3_KEY"
      - echo Upload to S3 completed on `date`
      - LAMBDA_S3_KEY="$MODULE_NAME/$AWS_S3_KEY"
      - aws lambda update-function-code --function-name "$FUNCTION_NAME" --s3-bucket "$BUCKET_NAME" --s3-key "$LAMBDA_S3_KEY"
      - echo Lambda function updated on `date`

