version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build -p handlers/$MODULE_NAME --scan

  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp handlers/$MODULE_NAME/build/libs/*-all.jar s3://$BUCKET_NAME/$MODULE_NAME/
      - echo Upload to S3 completed on `date`
