version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo Build started on `date`
      - ../../gradlew build --scan

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '*-all.jar'
  base-directory: 'build/libs'