version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - BUCKET=cdk-hnb659fds-assets-891377324743-us-east-1
      - echo Logging in to Amazon ECR...
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - ../../gradlew build

  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp /build/libs/save-user-info-all.jar s3://$BUCKET/lambda-artifacts/
